export const CART_ADD_ITEM = "CART ADD ITEM";
export const CART_REMOVE_ITEM = "CART REMOVE ITEM";
export const CART_CLEAR = "CART CLEAR";
export const SAVE_SHIPPING_ADDRESS = "SAVE SHIPPING ADDRESS";
export const SAVE_PAYMENT_METHOD = "SAVE PAYMENT METHOD";
