export const FETCH_DATA = "FETCH DATA";
export const FETCH_CATEGORIES = "FETCH CATEGORIES";
export const FETCH_SPECIFIC_CATEGORIES = "LOAD SPECIFIC CATEGORIES";
export const FETCH_HIGHEST_VALUE = "FETCH HIGHEST VALUE";
export const GET_ITEM = "GET ITEM";

export const SETUP_SHOP = "SETUP SHOP";
export const FILTER_BY_VALUE = "FILTER BY VALUE";
export const FILTER_BY_CATEGORY = "FILTER BY CATEGORY";
export const FILTER_BY_PRICE = "FILTER BY PRICE";
export const SORT_BY_NEW = "SORT BY NEW";
export const SORT_BY_ALPHABET = "SORT BY ALPHABET";
export const SORT_BY_PRICE = "SORT BY PRICE";
