//not in use, this is only the db architecture
//use only psql tables

const data = {
    products: [
        {
            name: "Maglietta",
            slug: "maglietta",
            categories: ["Maglie", "Abbigliamento", "Bambina"],
            tags: ["Abbigliamento", "Nike", "Scarpe", "Bambina"],
            images: ["/images/shirt1.jpg", "/images/shoes1.jpg"],
            price: 70,
            brand: "Nike",
            count_in_stock: 1,
            description: "A popular shirt",
            infos: "Infos vanno qua",
            condition: "new",
            related_products: [2],
            created_at: "2020-06-22 19:10:25-07",
        },
        {
            name: "Scarpe",
            slug: "scarpe",
            categories: ["Scarpe", "Abbigliamento", "Bambino"],
            tags: ["Abbigliamento", "Nike", "Scarpe", "Bambino"],
            images: ["/images/shoes1.jpg"],
            price: 40,
            brand: "Nike",
            count_in_stock: 1,
            description: "Some casual shoes",
            infos: null,
            condition: "used",
            related_products: [1, 3],
            created_at: "2020-06-22 19:10:25-07",
        },
        {
            name: "Game Boy",
            slug: "game-boy",
            categories: ["Giocattoli", "Videogiochi", "Elettronica"],
            tags: ["Giocattoli", "Videogiochi", "Game-Boy"],
            images: ["/images/gameboy.jpg"],
            price: 130,
            brand: "Nintendo",
            count_in_stock: 2,
            description: "Gameboy color come nuovo",
            infos: null,
            condition: "new",
            related_products: null,
            created_at: "2020-06-22 19:10:25-07",
        },
    ],
    users: [
        {
            id: 1,
            name: "Nicola Gaioni",
            email: "a@a.a",
            password: "xxxencrypted",
            is_admin: true,
            profile_pic_url: "/pics/Logo.jpg",
            created_at: "2020-06-22 19:10:25-07",
        },
    ],
    orders: [
        {
            order_id: 1,
            user_id: 1,
            order_items: [
                {
                    itemId: 1,
                    name: "Free Shirt",
                    slug: "free-shirt",
                    price: 70,
                    quantity: 1,
                    image: "/images/shirt1.jpg",
                },
                {
                    itemId: 2,
                    name: "Fit Shirt",
                    slug: "fit-shirt",
                    price: 40,
                    quantity: 1,
                    image: "/images/shirt2.jpg",
                },
            ],
            shipping_address: {
                fullName: "Nicola Gaioni",
                address: "Via Porto 1",
                city: "Cassone",
                postalCode: "37010",
                country: "Italy",
            },
            payment_method: "PayPal",
            payment_result: { id: "", status: "", email_address: "" },
            items_price: 15,
            shipping_price: 5,
            tax_price: 0.5,
            total_price: 15.5,
            is_paid: true,
            is_delivered: false,
            paid_at: "2020-06-22 19:10:25-07",
            delivered_at: null,
            created_at: "2020-06-22 19:10:25-07",
        },
    ],
};

export default data;
