export const SETUP_STORE = "SETUP STORE";
export const FILTER_BY_VALUE = "FILTER BY VALUE";
export const FILTER_BY_CATEGORY = "FILTER BY CATEGORY";
export const FILTER_BY_PRICE = "FILTER BY PRICE";
export const SORT_BY_NEW = "SORT BY NEW";
export const SORT_BY_ALPHABET = "SORT BY ALPHABET";
export const SORT_BY_PRICE = "SORT BY PRICE";
