import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/design-tokens.css";
import "../styles/globals.css";
import { DEFAULT_LOCALE } from "@/constants/config";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Providers from "@/components/Providers/Providers";

const geistSans = localFont({
    src: "../../public/fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "../../public/fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Da Mamy a Mamy",
    description: "Generated by create next app",
}; // TODO: Head stuff + SEO 🧠🔴

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang={DEFAULT_LOCALE}>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Providers>
                    <Header />
                    {/* <Nav /> */}
                    {children}
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
