export const LOAD_DATA = "LOAD DATA";
export const FETCH_CATEGORIES = "FETCH CATEGORIES";
export const FETCH_SPECIFIC_CATEGORIES = "LOAD SPECIFIC CATEGORIES";
export const FETCH_HIGHEST_VALUE = "FETCH HIGHEST VALUE";
export const GET_ITEM = "GET ITEM";
